### ISSUE TITLE
RabbitMQ Config Issue

### ISSUE THREAD

**Issue by ELHixon** [pivotalsoftware/newrelic_pivotal_agent#42]
The agent gets the following error when attempting to start:

[RabbitMQ] Exception while processing metrics. Check configuration.
stack level too deep

The configuration:
  rabbitmq:
    # Must enable rabbit management plugin
    # Note: When monitoring multiple nodes you should use the real hostnames instead of localhost
    # Uncomment the appropriate line for your version
    # RabbitMQ Default URL version 3.0
    #management_api_url: http://localhost:15672
    management_api_url: http://guest:guest@localhost:15672
    # RabbitMQ Default URL versions prior to 3.0
    #management_api_url: http://localhost:15672
    #
    # Set "debug: true" to see additional debug output
    # Note: This logs the metrics locally and does not send data to new relic.
    #debug: true

If I configure the URL without the credentials (http://localhost:15672) I get the following error:

[RabbitMQ] Exception while processing metrics. Check configuration.
the server responded with status 401

Running Rabbit 3.2.4. Rabbit management runs fine from a browser. Running on Windows Server 2012 R2.

**Comment by wesschlichter** [comment]
This was an issue which was fixed locally by me but not pushed out to github. Can you please verify that it is working with the latest version of master?

**Comment by joaosa** [comment]
I am also experiencing this issue

**Comment by premkumarbp3** [comment]
I am using master package but i got below exception.
[2018-01-24 12:30:11 UTC] INFO: Using Ruby SDK version: 1.3.1
[2018-01-24 12:30:11 UTC] INFO: Agent RabbitMQ is at version 1.0.5
[2018-01-24 12:30:11 UTC] INFO: Agent ModBmx is at version 1.0.5
[2018-01-24 12:30:11 UTC] INFO: Agent Redis is at version 1.0.5
[2018-01-24 12:30:11 UTC] DEBUG: Start collecting agent data for poll cycle
[RabbitMQ] Debug Mode On: Metric data will not be sent to new relic
[RabbitMQ] Exception while processing metrics. Check configuration.
execution expired
["/usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize'", "/usr/lib/ruby/2.3.0/net/http.rb:880:in `open'", "/usr/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'", "/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'", "/usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'", "/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'", "/usr/lib/ruby/2.3.0/net/http.rb:852:in `start'", "/usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'", "/usr/lib/ruby/2.3.0/net/http.rb:1156:in `get'", "/var/lib/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:78:in `perform_request'", "/var/lib/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:38:in `block in call'", "/var/lib/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'", "/var/lib/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:33:in `call'", "/var/lib/gems/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'", "/var/lib/gems/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/request/encode_json.rb:24:in `call'", "/var/lib/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'", "/var/lib/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'", "/var/lib/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'", "/var/lib/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/connection.rb:138:in `get'", "/var/lib/gems/2.3.0/gems/rabbitmq_manager-0.1.0/lib/rabbitmq_manager.rb:25:in `overview'", "/opt/newrelic_pivotal_agent-master/plugins/pivotal_rabbitmq_plugin/pivotal_rabbitmq_plugin.rb:94:in `queue_size_for'", "/opt/newrelic_pivotal_agent-master/plugins/pivotal_rabbitmq_plugin/pivotal_rabbitmq_plugin.rb:103:in `queue_size_ready'", "/opt/newrelic_pivotal_agent-master/plugins/pivotal_rabbitmq_plugin/pivotal_rabbitmq_plugin.rb:50:in `poll_cycle'", "/var/lib/gems/2.3.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/agent.rb:139:in `run'", "/var/lib/gems/2.3.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:143:in `block in run_agent_data_collection'", "/var/lib/gems/2.3.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:141:in `each'", "/var/lib/gems/2.3.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:141:in `run_agent_data_collection'", "/var/lib/gems/2.3.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:127:in `loop_forever'", "/var/lib/gems/2.3.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:15:in `setup_and_run'", "./pivotal_agent:51:in `<module:PivotalAgent>'", "./pivotal_agent:45:in `<main>'"]
[2018-01-24 12:31:11 UTC] DEBUG: Finished collecting agent data for poll cycle
[2018-01-24 12:31:11 UTC] DEBUG: Component with name "localhost:15672" and guid "com.pivotal.newrelic.plugin.rabbitmq" had no metrics
[2018-01-24 12:31:11 UTC] DEBUG: JSON payload: {"agent":{"version":"1.0.5"},"components":[]}
[2018-01-24 12:31:11 UTC] INFO: Gathered 0 statistics from 0 components

**Comment by fr33z3** [comment]
Any updates on that?
